   try{
window.aax = window.aax|| {};
window.aax.isLoaded = true;
var aaxSettings = {"srvd":"https:\/\/c.aaxads.com","pub":"AAX42WKKE","gdpr":"0","gdprconsent":"1","uspst":"0","uspcn":"","icr":"0","feedbackConfig":{"adIconConfig":{"206":{"id":"206","text":"ad","css":"background-color: #ffffff; color: #000000; border-color: #a1a1a1;"},"209":{"id":"209","text":"AD","css":"background-color: #ffffff; color: #0071bc; border-color: #ffffff;"},"212":{"id":"212","text":"ad","css":"background-color: rgba(0,0,0,.55); color: #ffffff; border-color: #ffffff;"},"241":{"id":"241","text":"AD","css":"background-color: #ffffff; color: #000000; border-color: #a1a1a1;"},"250":{"id":"250","text":"Ad","css":"background-color: rgba(0,0,0,.55); color: #ffffff; border-color: #ffffff;"}}},"logUrls":{"og":"https:\/\/l3.aaxads.com\/log","aaxdbg":"___stu13p=aveoaamactga5dnnuee25racpo4cuud1vi7rv"}};
var na="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ua="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function va(){va=function(){};ua.Symbol||(ua.Symbol=Ca)}var Ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function Ea(){va();var a=ua.Symbol.iterator;a||(a=ua.Symbol.iterator=ua.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&na(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return Ia(this)}});Ea=function(){}}function Ia(a){var b=0;return Ja(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function Ja(a){Ea();a={next:a};a[ua.Symbol.iterator]=function(){return this};return a}
function Ka(a,b){Ea();a instanceof String&&(a+="");var c=0,g={next:function(){if(c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g}for(var La=ua,Ma=["Array","prototype","keys"],Na=0;Na<Ma.length-1;Na++){var Oa=Ma[Na];Oa in La||(La[Oa]={});La=La[Oa]}var Pa=Ma[Ma.length-1],Qa=La[Pa],Ra=Qa?Qa:function(){return Ka(this,function(a){return a})};
Ra!=Qa&&null!=Ra&&na(La,Pa,{configurable:!0,writable:!0,value:Ra});
(function(){function a(a){return"function"===typeof a}function b(b,c,d){a(c)&&(d=c,c=[]);if(void 0===b||""===b||null===b||"[object Array]"!==Object.prototype.toString.call(c)||!a(d))return!1;k[b]=k[b]||{nE:c,callback:d}}function c(b,h){var d=[],f;for(f in b)if(b.hasOwnProperty(f)){var l=b[f];"object"===typeof l||"undefined"===typeof l?d.push(l):(void 0===g[l]&&(g[l]=c(k[l].nE,k[l].callback)),d.push(g[l]))}return a(h)?h.apply(this,d):d}var g={},k={};var h="undefined"!==typeof global&&"object"===typeof module?
global:window;h.__ar=h.__ar||c;h.__ad=h.__ad||b})();
__ad("_",["pqus","uhv",window,document,{}],function(a,b,c,g){function k(a,b,c){b="evt_"+(b||"gbl");U[b]=U[b]||{};U[b][a]=U[b][a]||[];U[b][a].push(c)}function h(a){if(l(a)){var b="evt_"+a;l(U[b])&&!n(U[b])&&ea(U[b],function(a,c){U[b][c]=[]})}}function f(b,c,d,f){f=f||("object"===typeof d?d:{});d="boolean"===typeof d?d:!1;var g="evt_"+(c||"gbl");if(void 0!==U[g]){var h=U[g][b]||[],k={src:c};U.evt_gbl&&U.evt_gbl.gblEvt&&a.$(U.evt_gbl.gblEvt[0],k,f);var l=0;for(c=h.length;l<c;l++)e(h[l])&&a.$(h[l],k,
f);!d&&0<h.length&&(U[g][b]=[])}}function m(a,b){return l(a)?l(b)&&-1!==a.indexOf(b):!1}function d(a,b){return p(a)?W(a,function(a){if(a===b)return!0})||!1:!1}function n(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0}function l(a){switch(typeof a){case "string":return void 0!==a&&""!==a&&null!==a;case "object":return null!==a;case "number":case "boolean":return!0;default:return!1}}function e(a){return"function"===typeof a}function p(a){return"[object Array]"===Object.prototype.toString.call(a)}
function q(a){return l(a)?encodeURIComponent(a):""}function r(a){if(!l(a))return"";try{return decodeURIComponent(a)}catch(ca){return a}}function u(a){if(!l(a))return{};var b={};var c=a.indexOf("?");if(-1===c)return b;a=a.substring(c+1).split("&");for(c=a.length;c--;){var d=a[c].split("=");b[d[0]]=d[1]}return b}function t(a){this.url=a;this.map=u(this.url)}function w(){var a=!1;try{"object"===typeof c.top&&"object"===typeof c&&(a=c.top!=c)}catch(ca){a=!0}return a}function v(a,b){a=Math.floor(Math.random()*
(b-a+1)+a);a>b&&(a=b);return a}function x(a,b,c){c=c||null;b=b||[];return function(){var d=b.slice(0);0<arguments.length&&Array.prototype.push.apply(d,Array.prototype.slice.call(arguments));return a.apply(c,d)}}function y(a){try{var b=A(a);return[b&&(b.document||b)||!1,b,null]}catch(ja){return[!1,null,"Access Denied"]}}function A(a){try{return a.contentWindow||a.contentDocument}catch(ca){return null}}function C(a){var b;a=a.match(/^([1-9]\d*|0[0-7]*|0x[\da-f]+)(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?(?:\.([1-9]\d*|0[0-7]*|0x[\da-f]+))?$/i);
if(!a)return!1;a[0]=0;for(b=1;5>b;b+=1)a[0]+=!!(a[b]||"").length,a[b]=parseInt(a[b],10)||0;a.push(256,256,256,256);a[4+a[0]]*=Math.pow(256,4-a[0]);return a[1]>=a[5]||a[2]>=a[6]||a[3]>=a[7]||a[4]>=a[8]?!1:a[1]*(1===a[0]||16777216)+a[2]*(2>=a[0]||65536)+a[3]*(3>=a[0]||256)+1*a[4]}function z(){return""+v(0,254)+"."+v(0,254)+"."+v(0,254)+"."+v(0,254)}function D(a,b,c,d,f){c=c||L("@body:0");if(!c)return N("@body:0",100,x(D,[a,b,null,d,f]),!1),null;var g=(new H).set("marginWidth",0).set("marginHeight",
0).set("scrolling","no").set("frameBorder",0).set("height",0).set("width",0).Hn("display:none !important;").done();l(a)&&(g.id=a);if(d)for(var h in d)g[h]=d[h];c.firstChild?c.insertBefore(g,c.firstChild):c.appendChild(g);b&&I(g,b);e(f)&&(g.onload=f);return g}function I(b,c){if(b){var d=y(b),e;try{if(null!==d[2])throw d[2];if(e=d[0])e.open(),e.write(c),e.close()}catch(Aa){d="javascript:var d=document.open();d.domain='"+g.domain+"';";b.src=d+"void(0);";try{var f=b.contentWindow.document;f.write(c);
f.close()}catch(ma){b.src=d+'d.write("'+c.replace(/"/g,'\\"')+'");d.close();',a.na(ma)}}}}function K(a,b,c){if(!l(a))return"";l(c)&&l(c.encode)&&!0===c.encode&&(b=q(b));return"&"+a+"="+b}function S(){return/msie|rv:11\.0/.test(X.toLowerCase())}function J(a){var b=[];ea(a.split("&"),function(a){-1!==a.indexOf("=")&&""!==a&&"action_object_map="!==a.substring(0,18)&&"action_type_map="!==a.substring(0,16)&&"action_ref_map="!==a.substring(0,15)&&"action_action_map="!==a.substring(0,18)&&"fb_"!==a.substring(0,
3)&&"fbclid"!==a.substring(0,6)&&"lcid="!==a.substring(0,5)&&"force_hbtest="!==a.substring(0,13)&&"mnet_test="!==a.substring(0,10)&&"force_hbprv="!==a.substring(0,12)&&"a="!==a.substring(0,2)&&"kwp_0"!==a.substring(0,6)&&"utm_"!==a.substring(0,4)&&"code="!==a.substring(0,5)&&"bcmt"!==a.substring(0,4)&&b.push(a)});return b.join("&")}function P(){if(m(X,"Trident")||m(X,"MSIE")){var a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(X);if(l(a)&&l(a[1]))return parseFloat(a[1])}return-1}function B(a,b){var d=/interactive|complete|loaded/;
g.attachEvent&&10>=P()&&(d=/complete|loaded/);if(d.test(g.readyState))a();else if(b||fa.U(c,"load",a),!b&&g.addEventListener)fa.U(g,"DOMContentLoaded",a);else if((b=g.documentElement)&&b.doScroll)try{b.doScroll("left"),a()}catch(sa){setTimeout(x(B,[a,!0]),50)}}function H(a){this.frame=a?a.document.createElement("iframe"):g.createElement("iframe")}function L(a){try{var b=a.substr(1).split(":"),c=b[0],d=l(b[1])&&parseInt(b[1],10);switch(a.charAt(0)){case "@":var e=g.getElementsByTagName(c);break;case "#":e=
g.getElementById(c);break;case "$":e=g.getElementsByName(c);break;case ".":e=V(g,c);break;default:e=g.getElementById(a)}return!1===d?e:e[d]}catch(Aa){return null}}function N(a,b,c,d){try{var e=L(a),f=ra.ic().Sm();e||!d&&f?c.call(null,e||!1):setTimeout(x(N,[a,b,c,d]),b)}catch(ma){setTimeout(x(N,[a,b,c,d]),b)}}function V(a,b,c){if(e(g.getElementsByClassName))return a.getElementsByClassName(b);c=c||"*";b=new RegExp("(^|\\s)"+b+"(\\s|$)");a=a||g;c="*"===c&&a.all?a.all:a.getElementsByTagName(c);a=[];var d=
c.length,f;for(f=0;f<d;f++){var h=c[f];b.test(h.className)&&a.push(h)}return a}function M(){return l(X)&&/ip(hone|od|ad)|android|blackberry|kindle|symbian|wap|windows (ce|phone)|palm( os)|iemobile|nokia|mobile/i.test(X)}function Y(){if(m(X,"Gecko")&&!m(X,"Trident")&&!m(X,"MSIE")||m(X,"webkit"))return!0;if(m(X,"Trident")||m(X,"MSIE")){var a=P();if(11<=a)return!0}return!1}function P(){if(m(X,"Trident")||m(X,"MSIE")){var a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(X);if(l(a)&&l(a[1]))return parseFloat(a[1])}return-1}
function aa(a){var b=a.toString(),c=b.indexOf(".");return-1!==c?parseFloat(b.substr(0,Math.min(c+3,b.length))).toFixed(2):parseFloat(a).toFixed(2)}function ba(a){return l(a)?!isFinite(a)||isNaN(a)?0:a:0}function da(){return-1!==c.location.href.indexOf("aax_test=")}function ia(a,b){if(null===b||"object"!==typeof b||!l(a))return b;ea(b,function(b,c){a[c]=ia(a[c],b)});return a}function ea(a,b){if(l(a)){var c=0,d=a.length;if(p(a))for(;c<d;c++)b.call(a[c],a[c],c,d);else for(c in a)a.hasOwnProperty(c)&&
b.call(a[c],a[c],c,0)}}function W(a,b){if(l(a)){e(b)||(b=function(a){return!!a});var c=0,d=a.length;if(p(a))for(;c<d;c++){var f=b.call(a[c],a[c],c);if(l(f))return f}else for(c in a)if(a.hasOwnProperty(c)&&(f=b.call(a[c],a[c],c),l(f)))return f}}function ha(a,b){if(!l(a))return[];var c;e(b)||(b=function(a){return!!a});var d=0,f=a.length;if(p(a))for(c=[];d<f;d++)c.push(b.call(a[d],a[d],d));else for(d in c={},a)a.hasOwnProperty(d)&&(c[d]=b.call(a[d],a[d],d));return c}function F(a){return"CSS1Compat"==
a.compatMode?a.documentElement:a.body}function G(a){var b=a.document,c=void 0,d=void 0;try{var e=F(b);if(!e){b.write('<div id="_mNTemp" style="display:none;"></div>');e=F(a.document);var f=g.getElementById("_mNTemp");f.parentNode.removeChild(f)}e&&(c=e.clientWidth||void 0,d=e.clientHeight||void 0)}catch(ma){}return{width:c,height:d}}function ka(){return!!(c.JSON&&c.JSON.parse&&"function"===typeof JSON.parse&&c.JSON.stringify&&"function"===typeof JSON.stringify)}function Q(){return(new Date).getTime()}
function O(a,b,c){c=c||"0";for(a+="";a.length<b;)a+=c;return a}function T(a,b){a=parseInt(a);return!isFinite(a)||isNaN(a)?b:a}function R(){return{MC:c.pageXOffset||c.scrollX,gr:c.pageYOffset||c.scrollY}}function Z(a){return null===a||"boolean"===typeof a||"number"===typeof a||"string"===typeof a||"symbol"===typeof a||"undefined"===typeof a}function la(a,b,c){la.count=la.count||0;la.threshold=la.threshold||c;setTimeout(function(){a.call(this);l(la.threshold)?(la.count++,la.count<la.threshold&&la(a,
b,c)):la(a,b,c)},b)}function Da(a,b){ea(b,function(b,c){Z(b)||p(b)||!a.hasOwnProperty(c)?a[c]=b:a[c]=Da(a[c],b)});return a}function Ba(a){return W(a,function(a){if(null!==a&&"object"===typeof a)return!0})||!1}function xa(a){if(!l(a))return a;var b=p(a)?[]:{};if(!Ba(a))return ea(a,function(a,c){b[c]=a}),b;ea(a,function(a,c){if(p(a)){var d=Ba(a)?xa(a):a.slice();b[c]=d}b[c]=null!==a&&"object"===typeof a?xa(a):a});return b}function ya(a){if(ka())return JSON.stringify(a);if(!l(a)||"object"!==typeof a)return null===
a?a+"":a;var b="";ea(a,function(c,d){void 0!==c&&("object"===typeof c&&(c=ya(c)),b=p(a)?b+c:b+(d+":"+c),b+=",")});b=b.slice(0,b.length-1);return p(a)?"["+b+"]":"{"+b+"}"}function qa(){try{if("localStorage"in c&&null!==c.localStorage)return c.localStorage.setItem("mntest","mntest"),c.localStorage.removeItem("mntest"),ka()}catch(E){}return!1}function za(a,b){var c=0;ha(a,function(a){b&&a[b]&&(c+=a[b])});return c}var U={},X=navigator.userAgent,pa=Math.random(),fa={U:function(a,b,c){a.addEventListener?
a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},tj:function(a,b,c){a.removeEventListener?a.removeEventListener(b,c):a.detachEvent&&a.detachEvent("on"+b,c)}};t.prototype.wG=function(){var a=this.map.dn;return a&&r(a)||""};var ra=function(){function b(){function b(){for(d=!0;0<e.length;){var a=e.shift();a.call(null)}e=[]}function c(){a.$(b)}var e=[];this.dd=function(a){e.push(a);1!==e.length||d?d&&c():B(c)};this.Sm=function(){return d}}var c=null,d=!1;return{ic:function(){null===
c&&(c=new b);return c}}}();H.prototype.set=function(a,b){this.frame[a]=b;return this};H.prototype.Hn=function(a){this.frame.style.cssText=a;return this};H.prototype.done=function(){return this.frame};return{uf:function(a){var b=g.cookie.indexOf(a+"="),c=b+a.length+1;if(!b&&a!==g.cookie.substring(0,a.length)||-1===b)return null;a=g.cookie.indexOf(";",c);-1===a&&(a=g.cookie.length);return unescape(g.cookie.substring(c,a))},io:function(a,b,c,d,e,f,h){var k=new Date;k.setTime(k.getTime());c&&(c*=864E5);
h&&(c=6E4*h);h=new Date(k.getTime()+c);g.cookie=a+"="+escape(b)+(c?";expires="+h.toGMTString():"")+(d?";path="+d:"")+(e?";domain="+e:"")+(f?";secure":"")},In:O,N:q,rc:r,Lv:function(a){return r(a)!==a},iL:function(a){return m(X.toLowerCase(),a)},iO:function(a){var b=a.length;for(a=(a||"0123456789abcdefghijklmnopqrstuvwxyz").split("");b;){var c=Math.floor(Math.random()*b);--b;var d=a[b];a[b]=a[c];a[c]=d}return a.join("")},Wc:function(a,b){return!l(a)&&l(b)?null:(a=(new RegExp("[?&]"+b+"=([^&#]*)","i")).exec(a))?
a[1]:null},zc:function(a){a=r(a);return(a=a.match(/^http(?:s)?:\/\/([^/]+)/im))?a[1].toString():""},M:function(){return l(c.location.href)?c.location.href:""},nh:function(a){return"string"===typeof a},Gv:function(a){return"boolean"===typeof a},K:function(a){return l(a)},Cc:w(),nga:w,sa:v,wu:function(a,b,c){c=Math.pow(10,c||2);return v(a*c,b*c)/c},qG:function(){var a=new Date;a=new Date(Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()));var b=new Date(Date.UTC(a.getUTCFullYear(),0,1));a.setUTCDate(a.getUTCDate()+
4-(a.getUTCDay()||7));return Math.ceil(((a-b)/864E5+1)/7)},vm:u,Pz:t,LD:function(a){return l(a)?-1!==a.search("^(http(s)?%253A%252F%252F)")?r(a):-1!==a.search("^(http(s)?://)")?q(a):a:""},W:fa,f:e,isArray:p,Fj:c.navigator.userAgent.toLowerCase(),oK:Y(),wa:function(a,b,c){var d={};l(c)&&l(c.encode)&&(d.encode=c.encode);c="";var e,f=!!b,g=f?b:a,h;for(e in g)if(g.hasOwnProperty(e)){f&&(e=b[e]);if(h=l(a[e]))h=a[e],h="object"!==typeof h||!1!==h.lL;if(h)if(p(a[e]))for(var k in a[e])c+=K(e+"[]",a[e][k],
d);else h="object"===typeof a[e]?a[e].value:a[e],c+=K(e,h,d)}return c},za:K,pga:function(a){switch(typeof a){case "string":return l(a)&&("1"===a||"true"===a);case "number":return 0!==a;case "boolean":return a;default:return!1}},Z:d,zf:y,Ng:A,B:x,Wj:H,Pc:N,hc:V,zv:C,yN:function(a){var b=a.lastIndexOf(".");return-1===b?"":a.substr(0,b+1)+"0"},wi:m,T:L,af:function(a,b){a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)},Pw:function(a){a.parentNode.removeChild(a)},Re:I,Aga:function(a,b){I(a,
'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; }};scriptElement.src = "'+b+'"; tag.parentNode.insertBefore(scriptElement, tag);}\x3c/script></head><body onload="makeCall()"></body></html>')},
pha:function(a,b){if(void 0!==a&&void 0!==b&&void 0!==a[b])return a[b]},Ic:ra,oga:M,NK:function(){return l(X)&&/mac_powerpc|macintosh|mac\\sos|darwin\/|imac\/|macbookpro[\d]/i.test(X)},rd:D,oh:function(b,c,d,e){if(l(b)){"http"!==b.substr(0,4)&&!0===d&&(b=("https:"===g.location.protocol?"https:":"http:")+b);d=g.createElement("script");var f=g.getElementsByTagName("script")[0],h=!1;d.type="text/javascript";d.async=!0;e&&e.crossOrigin&&(d.crossOrigin="anonymous");c&&"function"===typeof c&&(d.onload=
d.onreadystatechange=function(){h||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(h=!0,a.$(c))});d.src=b;f.parentNode.insertBefore(d,f)}},aj:function(a){if(l(a)){var b=g.createElement("script"),c=g.getElementsByTagName("script")[0];b.type="text/javascript";b.appendChild(g.createTextNode(a));c.parentNode.insertBefore(b,c)}},vL:function(a,b,c){if(l(a)){"http"!==a.substr(0,4)&&(a=("https:"===g.location.protocol?"https:":"http:")+a);var d="aax_if"+c;k("prvreq",c,b);a=D(d,
'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; window.parent.__ar([\'_\'], function(util){util.triggerEvent(\'prvreq\', "'+
c+'", false, window);});}};scriptElement.src = "'+a+'"; tag.parentNode.insertBefore(scriptElement, tag);}if(("performance" in window) && ("PerformanceObserver" in window)) {var observer = new PerformanceObserver(function (entries) {try {window.parent.aax.processPrefetchPerformanceEntries(entries.getEntries());} catch (e) {}});observer.observe({entryTypes: [\'resource\']});} \x3c/script></head><body onload="makeCall()"></body></html>');return y(a)[1]}},triggerEvent:f,Rx:function(a,b,c,d){f("b:"+a,
b,c);f(a,b,c,d);f("a:"+a,b,c)},A:k,dga:function(a,b,c){var d=!1;p(a)&&l(b)&&l(c)&&(ea(a,function(e,f){!0===(new RegExp(b)).test(e)&&(d=!0,a[f]=c)}),!1===d&&a.push(c))},oa:aa,gf:function(){da()&&c.console&&c.console.log(Array.prototype.slice.call(arguments))},nn:da,xu:z,Lea:function(a,b,c){var d=[],e,f=[],g={};if(0===a.length)return[""];l(c)&&l(c.encode)&&(g.encode=c.encode);for(m in a[0])a[0].hasOwnProperty(m)&&d.push(m);var h="",k=S();var m=0;for(c=a.length;m<c;m++){var n="";var p=0;for(e=d.length;p<
e;p++)n+=K(d[p]+"[]",a[m][d[p]],g);k&&l(b)?n.length>b?f.push(n):(h+n).length>b?(f.push(h),h=n):h+=n:h+=n}f.push(h);return f},si:function(a,b){var c="",d={};l(b)&&l(b.encode)&&(d.encode=b.encode);ea(a,function(a,b){c+=K(b,a,d)});return c},o:function(a,b){a.Lha=b;for(var c in b.prototype)a.prototype[c]=b.prototype[c];a.prototype.constructor=a},jj:function(a,b){b*=6E4;return Q()-a>b?!1:!0},C:new function(){var a={},b,c=!1;this.startTime=function(){return b};this.start=function(){b=(new Date).getTime();
c=!0};this.stop=function(){(new Date).getTime();c=!1};this.Uc=function(){return(new Date).getTime()-b};this.fa=function(b){a[b]={};a[b].startTime=c?this.Uc():-1};this.pa=function(b){a.hasOwnProperty(b)&&(a[b].endTime=-1===a[b].startTime?-1:this.Uc())};this.time=function(b){return a.hasOwnProperty(b)?(a[b].endTime||this.pa(b),a[b].endTime-a[b].startTime):-1};this.getTime=function(b){return a.hasOwnProperty(b)?this.Uc()-a[b].startTime:-1}},extend:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=
b[c]);return a},On:ia,Gb:function(){try{return/loaded|complete/.test(g.readyState)}catch(E){return!1}},qfa:function(a,b){b="evt_"+(b||"gbl");U[b]&&U[b][a]&&0<U[b][a].length&&(U[b][a]=[])},iha:function(){for(var a in U)U.hasOwnProperty(a)&&-1!==a.indexOf("evt_")&&-1===a.indexOf("cmd")&&(U[a]={})},jha:h,kha:function(){h("gbl")},a:l,kK:function(a){return"undefined"!==typeof a},trim:function(a){return l(a)?a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""):""},I:n,Kd:function(a){return"object"===typeof a&&
null!==a&&!n(a)},Lr:function(a){if(!p(a))return{};for(var b=0,c=a.length,d={};b<c;b++)d[a[b]]=b+1;return d},map:ha,reduce:function(a,b,c){if(e(b)){if(p(a)){var d=0;var f=a.length;if("undefined"===typeof c){for(;d<f&&!(d in a);)d++;if(d>=f)return;c=a[d++]}for(;d<f;d++)d in a&&(c=b(c,a[d],d,a));return c}c=c||"";for(d in a)a.hasOwnProperty(d)&&(c=b(c,a[d],d,a));return c}},filter:function(a,b){if(!l(a))return[];var c;e(b)||(b=function(a){return!!a});var d=0,f=a.length;if(p(a))for(c=[];d<f;d++)b.call(a[d],
a[d],d)&&c.push(a[d]);else for(d in c={},a)a.hasOwnProperty(d)&&b.call(a[d],a[d],d)&&(c[d]=a[d]);return c},Sc:function(a,b){b=b.split(".");var c;for(c=0;c<b.length;++c){if(void 0===a[b[c]])return;a=a[b[c]]}return a},u:W,some:function(a,b){if(!l(a))return!1;e(b)||(b=function(a){return!!a});var c=0,d=a.length;if(p(a))for(;c<d;c++){var f=b.call(a[c],a[c],c);if(!0===f)return f}else for(c in a)if(a.hasOwnProperty(c)&&(f=b.call(a[c],a[c],c),!0===f))return f;return!1},c:ea,Us:S,re:G,Gg:function(){return G(c).width},
Wl:function(){return G(c).height},MI:function(){try{return c.screen.width+"x"+c.screen.height}catch(E){return""}},we:ka,ca:Q,vh:function(a,b){b=Math.pow(10,b);return Math.round(a*b)/b},Xf:function(a){return(a||"").replace(/\/$/,"")},Si:function(a){if(e(Object.keys))return Object.keys(a);var b=[];ea(a,function(a,c){b.push(c)});return b},DH:function(a){if(p(a)&&(a=Math.max.apply(null,a),!isNaN(a)))return a},Hga:function(a,b){if("object"!==typeof a||"string"!==typeof b)return!1;if("string"===typeof a.className)return(new RegExp("(^|\\s)"+
b+"(\\s|$)")).test(a.className)},Sd:function(a,b,c){var d=e(c)?c:Date.now,f=d();return function(){var c=d();c-f>=a&&(f=c,b.apply(null,arguments))}},Ma:function(a,b){return a.style[b]?a.style[b]:a.currentStyle?a.currentStyle[b]:g.defaultView&&g.defaultView.getComputedStyle?(b=b.replace(/([A-Z])/g,"-$1"),b=b.toLowerCase(),(a=g.defaultView.getComputedStyle(a,""))&&a.getPropertyValue(b)):null},Ex:function(a){l(a)&&(a.style.cssText=(a.style.cssText||"")+";display:block!important;")},jv:function(a){l(a)&&
(a.style.cssText=(a.style.cssText||"")+";display:none!important;")},xi:function(d,e,f,g){function h(){(f.onerror||m)()}function k(){(f.onload||m)(n.response||n.responseText)}function m(){}if(!c.XMLHttpRequest)return(f.Fl||m)(),null;var n=new XMLHttpRequest,p=!1;d=(d||b.$y.M7).toUpperCase();if("withCredentials"in n)n.open(d,e,!0),n.withCredentials=l(f.withCredentials)?f.withCredentials:!0;else if(c.XDomainRequest){n=new XDomainRequest;try{n.open(d,e)}catch(Ha){return(f.Fl||m)(),null}}else return(f.Fl||
m)(),null;n.onload=n.onreadystatechange=function(){p||4!=n.readyState||(200==n.status?a.$(k):h(),p=!0)};n.onerror=h;n.onabort=h;n.send(g);return!0},Xt:P,xm:function(a){var b;try{a&&a.data&&"string"===typeof a.data&&ka()&&(b=JSON.parse(a.data))}catch(ja){}return b},tn:function(){return e(c.navigator.sendBeacon)?!0:!1},gK:function(){return"withCredentials"in new XMLHttpRequest||"undefined"!=typeof XDomainRequest?!0:!1},kH:function(a){function b(a){a=a.match(/\d+/g);return null===a||0===a.length?"":
a[0]}a=a.frameElement;var c=String(a.height||"0"),d=String(a.width||"0");-1!==c.indexOf("%")||-1!==d.indexOf("%")?(d=a.getBoundingClientRect&&a.getBoundingClientRect()||{},c=Math.ceil(d.height||a.clientHeight)||0,d=Math.ceil(d.width||a.clientWidth)||0):(c=b(c),d=b(d));return d+"x"+c},eJ:function(){try{var a=c.localStorage}catch(ca){}return l(a)&&(a=a.getItem("tpck"),l(a))?a:!1===(c&&c.navigator&&c.navigator.cookieEnabled||navigator&&navigator.cookieEnabled)?0:""},Jt:function(a){a=L("#"+a);var b={},
c=R().MC,d=R().gr,f={};l(a)&&e(a.getBoundingClientRect)&&(f=a.getBoundingClientRect());b.Qha=T(f.top,0);b.Gea=T(f.bottom,0);b.zga=T(f.left,0);b.mha=T(f.right,0);b.top=T(f.top+d,0);b.bottom=T(f.bottom+d,0);b.left=T(f.left+c,0);b.right=T(f.right+c,0);b.offsetX=T(c,0);b.offsetY=T(d,0);return b},Oa:function(){var a=Array.prototype.slice.call(arguments),b=a[0];a.shift();ea(a,function(a){p(a)?Array.prototype.push.apply(b,a):b.push(a)});return b},Xa:T,Request:function(a){var b={};this.input=function(a,c){b[a]=
c;return this};this.get=function(a){return l(b[a])?b[a]:""};this.lw=function(a){a&&(b=a);return this};this.freeze=function(){return b};this.deleteProperty=function(a){delete b[a]};a&&(b=a)},fs:function(a){if(!l(a))return"";var b=a.split("?")[0].split("#")[0];if(!l(b))return"";b=b.replace(/\/$/,"");var c=a.indexOf("#"),d="";0<c&&(d=a.substring(c+1));var e=a.indexOf("?");c=0<c?c:a.length;var f="";0<e&&(f=a.substring(e+1,c));a=J(f);l(a)&&(b=b+"?"+a);d=J(d);l(d)&&(b=b+"#"+d);return b},bM:function(a,b){try{return Y()?
(a.document.write(b),a.document.close()):(a.hbContent="<!DOCTYPE html><html><head></head><body>"+b+"</body></html>",a.location.replace('javascript:window["hbContent"];')),!0}catch(ja){return!1}},hf:function(a,b,c){return(new H).set("marginWidth",0).set("marginHeight",0).set("scrolling","no").set("frameBorder",0).set("height",c||0).set("width",b||0).set("id",a).set("allowtransparency","true").done()},rn:Z,fD:function(a,b){l(b)||(b=0);return new Date(a.getTime()+6E4*b)},fM:la,L:function(b,c){return"function"===
typeof b?x(a.$,[c||null,b]):b},Ti:function(){try{var a=c.document.body,b=c.document.documentElement;return Math.max(a.scrollHeight,a.offsetHeight,b.clientHeight,b.scrollHeight,b.offsetHeight)}catch(ja){return 0}},sga:function(){return!1},ka:function(){return O(C(z()),10)+""+v(1E6,9999999)+""+(new Date).getTime().toString()},Lb:function(a,b){return a*(1+b/100)},Zw:ba,getFloatValue:function(a){a=ba(a);a=aa(a);return parseFloat(a)},Hw:Da,ss:xa,Wb:function(a){return l(a)&&(1>a||1<a*pa)},Vg:function(){return("https:"===
c.location.protocol?"https:":"http:")+"//"+c.location.hostname},KL:ya,cl:function(a){return"http"!==a.substr(0,4)?("https:"===g.location.protocol?"https:":"http:")+a+a:a},EO:function(a,b){return a.length>b?a.substr(0,b):a},SH:R,hJ:function(a){for(var b=a.parent;b!==c.top;)a=a.parent,b=b.parent;return a},Dfa:function(a){(new Image).src=a},postMessage:function(a,b,d){var f=A(d);b&&l(f)&&(c.postMessage&&e(f.postMessage)?f.postMessage(a,"*"):b&&("object"===typeof a&&(a=ya(a),a=escape(a)),b=b+"#"+g.location.href,
d.src=b,f.location=b.replace(/#.*$/,"")+"#_CPM$"+a))},vK:function(){return!!c.EventSource},Ne:qa,Zi:function(){return M()&&!qa()},kI:function(a,b){if(b){var c=za(a,b),d=v(0,100),e=0,f=null;return 1>c||100<c?f:f=W(a,function(a){if(a[b]&&(e+=a[b],d<e))return a})}},Yr:function(a,b){return p(a)&&p(b)?W(a,function(a){return d(b,a)}):!1},kJ:function(){return c.navigator&&c.navigator.vendor},lh:function(){if(-1!==navigator.userAgent.indexOf("CriOS")||-1!==navigator.userAgent.indexOf("FxiOS"))return!1;var a=
navigator.userAgent.toLowerCase();a=-1!==a.indexOf("safari")&&-1===a.indexOf("chrome")||!1;return navigator.vendor&&-1<navigator.vendor.indexOf("Apple")||a},dH:function(a){var b=L("@head:0");if(b)return b.getAttribute(a)||""},IG:function(a){return l(a)&&"undefined"!==typeof a?a.getAttribute("id")||a.id:""},uj:function(a,b,c){return a.replace(new RegExp(b,"g"),c)},em:function(a){for(var b=c,d;b;){try{if(b.frames[a]){d=b;break}}catch(sa){}if(b===c.top)break;b=b.parent}return d},WG:function(a){return a.frameElement}}});
__ad("pqus",[window,document,{}],function(a,b){function c(){var g,h=0;for(g=0;3>g;g++)h+=e[g].length;if(0!==h){var k=new Image,n=("https:"===b.location.protocol?"https":"http")+"://l3.aaxads.com/nerrping.php",t="",w=0;for(g=2;0<=g;g--){for(h=e[g].length;0<h;){var v=1===g?e[g][0]:{logLevel:e[g][0].logLevel,errorVal:{name:e[g][0].errorVal.name,type:m,svr:d,message:e[g][0].errorVal.message,line:e[g][0].errorVal.lineNumber,description:e[g][0].errorVal.description,stack:e[g][0].errorVal.stack}};v="object"===
typeof JSON&&"function"===typeof JSON.stringify?JSON.stringify(v):void 0;if(1200>=v.length+t.length||!t.length)0!==t.length&&(t+=","),t+=v,e[g].shift(),h--;else{w=1;break}}if(w)break}t=encodeURIComponent("["+t+"]");g=n+"?d="+t+"&userAgent="+l+"&requrl="+encodeURIComponent(a.location.href)+"&img=logo.gif";k.src=g}f(c,2500)}function g(a){"undefined"===typeof a.logLevel&&(a={logLevel:3,errorVal:a});3<=a.logLevel&&e[a.logLevel-1].push(a)}function k(a,b,c){this.name=a;this.message=b;this.logLevel=c}function h(){var a=
Array.prototype.slice.call(arguments),b=a.length,c=null,d=null;if("object"===typeof a[b-1]&&null!==a[b-1]&&a[b-1].constructor===k){var e=a[b-1];b--}if("function"===typeof a[0]){var f=a.shift();b--}else c=a.shift(),f=a.shift(),b-=2;a=a.slice(0,b);try{return f.apply(c,a)}catch(v){return e&&(v.name=e.name+" ("+v.name+")",v.message=e.message+" ("+v.message+")",d=e.logLevel),g({logLevel:d||3,errorVal:v}),new k}}function f(b,c){if("function"===typeof b)return a.setTimeout(function(){h(b)},c)}var m="",d=
"",n,l=encodeURIComponent(navigator.userAgent),e=[];for(n=0;3>n;n++)e[n]=[];a.addEventListener("load",c);return{$:h,na:g,Gh:function(a){m=a},fx:function(a){d=a},Cha:function(){},setTimeout:f}});
__ad("qlf",["pqus",window,"_","uhv","performanceobserver"],function(a,b,c,g,k){function h(a){var b=c.extend({},l);return a=c.extend(b,a)}function f(b,d,f){!0===d.Rs&&(b=c.cl(b));c.a(d.Mr)&&c.c(d.Mr,function(a,b){e.setAttribute(b,a)});var e=document.createElement("script");d=document.getElementsByTagName("script")[0];var g=!1;e.type="text/javascript";e.async=!0;f&&"function"===typeof f&&(e.onload=e.onreadystatechange=function(){g||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||
(g=!0,a.$(f))},e.onerror=function(){f.call(null,"error")});e.src=b;d.parentNode.insertBefore(e,d)}function m(a,b){var d=new Image;a=c.EO(a,8E3);d.onload=b;d.src=a;d.onerror=function(){b.call(null,"error")}}function d(a,b){var d=new XMLHttpRequest,e="POST"===b.method?a.url:a;if(!("withCredentials"in d))return d=new XDomainRequest,d.open(b.method,a),d;d.open(b.method,e,!0);d.withCredentials=c.a(b.withCredentials)?b.withCredentials:!0;return d}function n(a,b,c){var e=!1,f=a.payload;try{var g=d(a,b)}catch(w){c.call(null,
500,"error")}g.onload=g.onreadystatechange=function(){if(!e&&4===this.readyState)return e=!0,200===this.status?c.call(null,null,this.response||this.responseText):c.call(null,this.state,"error")};g.send(f)}var l={X:["plvf"],method:"GET",type:"img",Rs:!1};return{submit:function(a,d,g){c.isArray(a)||(a=[a]);d=h(d);g=g||function(){};c.c(a,function(a){var e=k.B(a,d,g);switch(d.type){case "img":m(a,e);break;case "script":f(a,d,e);break;case "xhr":n(a,d,e);break;case "sb":e=d;c.tn()&&(a=!1===b.navigator.sendBeacon(a.url,
a.payload)?"error":"success",k.Cr(e,a));break;case "ifScr":var h=d;a=c.cl(a);c.A("prvreq",h.name,e);a=c.rd("",'<!DOCTYPE html><html><head><script type="text/javascript">function makeCall(){var scriptElement = document.createElement(\'script\'), tag = document.getElementsByTagName("script")[0], status = false; scriptElement.type = \'text/javascript\'; scriptElement.async = true; scriptElement.onload = scriptElement.onreadystatechange = function () { if (!status && (!this.readyState || this.readyState === "loaded" || this.readyState === "complete")) { status = true; window.parent.__ar([\'_\'], function(util){util.triggerEvent(\'prvreq\', "'+
h.name+'", false, window);});}};scriptElement.src = "'+a+'"; tag.parentNode.insertBefore(scriptElement, tag);}if(("performance" in window) && ("PerformanceObserver" in window)) {var observer = new PerformanceObserver(function (entries) {try {window.parent.aax.processPrefetchPerformanceEntries(entries.getEntries());} catch (e) {}});observer.observe({entryTypes: [\'resource\']});} \x3c/script></head><body onload="makeCall()"></body></html>');c.zf(a)}})},stream:function(a,c,d){d=d||function(){};c=h(c);
var e=k.B(a,c,d);try{var f=new b.EventSource(a,{withCredentials:!0})}catch(t){e.call(null,"error")}"undefined"!==typeof f&&(f.onopen=e,f.onerror=function(){e.call(null,"error")});return f}}});
__ad("performanceobserver",function(){return{B:function(a,b,c){return c},Cr:function(){}}});
__ad("srvwpf",function(){return{D:{},Zd:{},Se:{}}});
__ad("ff",function(){return{PROVIDER_IDS:{},Yo:{},Hz:{},Rz:{},Ba:{},Cz:{},gk:{},RB:{},Ue:{},UA:{}}});
__ad("ef",function(){return{$j:{},$f:{},Sh:{},D:{},wk:{},zk:{},Xe:{},Yd:{},Zd:{}}});
__ad("of",function(){return{ei:{},zp:{},nq:{},xq:{},Aq:{},oy:{},zb:{},$f:{},ik:{},jz:{},HC:{},fi:{},pB:{},Se:{},jk:{},Xe:{}}});
__ad("postdataconstants",function(){return{D:{}}});
__ad("uhv",function(){return{Event:{},Zy:{},zz:{},QA:{},EC:{},Hy:{},Yy:{},gk:{},Se:{},xC:{}}});
__ad("aaxframelogmanager",[window.aaxSettings,"_","of","uhv","inmemdatasource"],function(a,b,c,g,k){return{sea:function(c){var f={};f.hyw=c;f.flg=a.pub;f.jgsu=k.get("gdpr")?"1":"0";c=a.logUrls&&a.logUrls.og;var g=a.logUrls&&a.logUrls.aaxdbg;(new Image).src=c+"?"+g+b.wa(f)}}});
__ad("inmemdatasource",["_","uhv"],function(a){function b(){var b={};this.set=function(c,g){a.a(c)&&a.rn(c)&&(b[c]=g);return this};this.get=function(a){return b[a]||""}}function c(c){if(!a.a(c)||!a.rn(c))return null;c=c.toString();a.a(g[c])||(g[c]=new b);return g[c]}var g={},k={};return{set:function(a,b){return c("primary_in_mem_resource").set(a,b)},get:function(a){return c("primary_in_mem_resource").get(a)},UN:function(a,b){k[a]=b},dh:function(a){k[a]||(k[a]=[]);return k[a]},for:c}});
__ad("ie","feedbackuimanager _ srvwpf postdata ff uhv inmemdatasource".split(" "),function(a,b,c,g,k,h,f){function m(){var a={};this.input=function(c,e){var d=/[$]{([A-Za-z_]+)}/g.exec(c);b.a(d)&&b.isArray(d)&&d[1]&&(c=d[1]);a[c]=e;return this};this.om=function(){return a}}function d(a,c){this.resolve=function(){return b.a(a)?a.replace(/[$]{([A-Za-z_]+)}/g,function(a,e){a=c[e];return b.a(a)?a:""}):""}}function n(a,c,e){if(!b.a(a)||!b.a(c)||!b.a(e))return!0;var d=b.some(a.placements,function(a){return a===
c});b.a(a.placements)||(d=!0);var f=b.some(a.providers,function(a){return a===e});b.a(a.providers)||(f=!0);return d&&f&&b.a(a.enabled)?a.enabled:!0}function l(a){a=(new g).set("type","feedback").set("aId",f.get("aid")).set("rate",a.Pd).set("dist",a.reason&&a.reason.distracting).set("ntRel",a.reason&&a.reason.notrelevant).set("prLb",a.reason&&a.reason.poorlylabeled).set("misL",a.reason&&a.reason.misleading).set("toob",a.reason&&a.reason.toobig);a.target(f.get("tarOg"));a.Qb(f.get("fid"));window.top.postMessage(a.Y(),
a.target())}function e(b){function c(){l(d.ft())}var e={Hl:3,px:!0,Rc:{right:"0px",bottom:"0px"},qw:"//c.aaxads.com",Cn:"v1"},d=a(e,b);d.wO(function(a){a>e.Hl&&l(d.ft())});d.vO(c);d.uO(c);d.init();return d}return{Zm:function(a,c){var f=(b.a(a)?a:window).document,g='<span id="aax-ad-icon" class="advertisement-on-ad" ${ad_mark_block_css}>${ad_mark_block_text}</span>',l="AD",h="",k=(window.aaxSettings.feedbackConfig||{}).adIconConfig;b.a(c)&&b.a(k)&&(c=k[c],b.a(c)&&(b.a(c.text)&&(l=c.text),b.a(c.css)&&
(h='style="'+c.css+'"')));c=new m;c.input("${ad_mark_block_text}",l).input("${ad_mark_block_css}",h);g=(new d(g,c.om())).resolve();l=f.createElement("div");for(l.innerHTML=g+'<div id="aax-feedback" class="container aax-popup hide"> <div class="popup-container"> <div class="logo-wrapper"> </div><div class="rating-block-wrapper"> <div class="aax-rating-block"> <div class="aax-rating hide"> <div class="aax-rating-text-wrapper"> <p class="aax-rating-text">We use user feedback to show better ads</p></div><div class="aax-stars-wrapper"> <p>Rate this Ad</p><ul class="star-list"> <li data-rate="5"></li><li data-rate="4"></li><li data-rate="3"></li><li data-rate="2"></li><li data-rate="1"></li></ul> </div></div><div class="aax-rating-feedback hide"> <ul class=""> <li> <label for="distracting"> <input type="checkbox" name="distracting" value="distracting" id="distracting"> <span class="checkmark"></span> Distracting </label> </li><li> <label for="poorlylabeled"> <input type="checkbox" name="poorlylabeled" value="poorlylabeled" id="poorlylabeled"> <span class="checkmark"></span> Poorly Labeled </label> </li></ul> <ul class=""> <li> <label for="toobig"> <input type="checkbox" name="toobig" value="toobig" id="toobig"> <span class="checkmark"></span> Too Big </label> </li><li> <label for="notrelevant"> <input type="checkbox" name="notrelevant" value="notrelevant" id="notrelevant"> <span class="checkmark"></span> Not Relevant </label> </li></ul> <ul class="last-column"> <li> <label for="misleading"> <input type="checkbox" name="misleading" value="misleading" id="misleading"> <span class="checkmark"></span> Misleading Ad </label> </li></ul> <span class="submit"> <button type="button" name="button">Submit</button> </span> </div><div class="aax-rating aax-rating-last hide"> <p> <i></i> <span>Thanks for submitting the feedback</span> </p></div></div></div><p class="aax-optout hide"> Cookies help us deliver our services better. Click here to <a href="https://optout.aaxads.com" target="_blank">Opt Out</a>. </p></div><span class="close-feedback"> <i></i> </span></div><span id="aax-feedback-icon" class="feedback-cta"> <i></i> </span>';l.firstChild;)f.body.appendChild(l.firstChild);
return e(a)},qr:function(a){a=(b.a(a)?a:window).document;var c=a.createElement("link");c.rel="stylesheet";c.type="text/css";c.href="//c.aaxads.com/aax-style.css";a.getElementsByTagName("head")[0].appendChild(c)},Xr:function(a,c){a=parseInt(a,10);c=parseInt(c,10);var e=b.T("#aax-ad-icon"),d=b.T("#aax-feedback-icon"),f=c,g=window.aaxSettings.feedbackConfig||{};c=n(g.adIcon,a,f);a=n(g.fdIcon,a,f);c?b.Ex(e):b.jv(e);a?b.Ex(d):b.jv(d)}}});
__ad("feedbackuimanager",function(){return function(a,b){a=a?a:{};if(b&&b.document){var c=b.document,g={top:"auto",right:"auto",bottom:"auto",left:"auto"},k={ob:"#aax-feedback",Hl:3,sg:".feedback-cta",Lo:null,Ko:null,px:!1,Rc:null,qw:"images",Cn:null},h={},f={Pd:null,reason:{}},m=[],d=[],n=[],l={},e=!1,p=function(b,e){var d=c.querySelector(a.ob+" .logo-wrapper"),f=c.createElement("IMG");f.src=a.qw+"/"+e+(null===a.Cn?"":"?ver="+a.Cn);f.alt="AAX";f.className="portrait"===b?"logo logo-portrait":"logo logo-standard";
d.appendChild(f)},q={f:function(a){return"[object Function]"==={}.toString.call(a)},oi:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},xJ:function(a,b){return-1<a.className.indexOf(b)},be:function(a,b){if(!q.xJ(a,b)){var c=a.className.split(" ");c.push(b);a.className=c.join(" ")}return a},jd:function(a,b){a.className=a.className.replace(b,"").replace(/\s{2,}/g," ").replace(/^\s\s*/,"").replace(/\s\s*$/,"");return a},Pl:function(a){var b=[];a=c.querySelectorAll(a+
" input");for(var e=0;e<a.length;e++)a[e].checked&&b.push(a[e]);return b},zN:function(){var e="",d=c.querySelector(a.ob),f=c.documentElement,g=c.getElementsByTagName("body")[0],l=b.innerWidth||f.clientWidth||g.clientWidth;f=b.innerHeight||f.clientHeight||g.clientHeight;q.jd(d,"portrait");q.jd(d,"landscape");q.jd(d,"standard");l<f?e="portrait":675<=l?e="landscape":225<=l&&(e="standard");"portrait"===e&&360>f?e="basic-small portrait":"landscape"===e&&90>f?e="basic-small horizontal":"standard"===e&&
220>f&&(e="basic-small horizontal");-1<e.indexOf("portrait")?p("portrait","logo-vertical.png"):p("landscape","logo.png");q.be(d,e)},hN:function(){for(var b in g)g.hasOwnProperty(b)&&(a.Rc.hasOwnProperty(b)||(a.Rc[b]=g[b]))},gN:function(){var b=c.querySelector(a.sg);b.style.top=a.Rc.top;b.style.right=a.Rc.right;b.style.bottom=a.Rc.bottom;b.style.left=a.Rc.left}},r={NN:function(b){f.Pd=(b.target||b.srcElement).getAttribute("data-rate");for(b=0;b<m.length;b++)m[b].call(l,f.Pd);f.Pd<=a.Hl?r.show(".aax-rating-feedback"):
r.show(".aax-rating-last")},pN:function(){for(var b=q.Pl(a.ob+" .aax-rating-feedback"),c=0;c<b.length;c++)f.reason[b[c].value]=1,b[c].checked=!1;for(b=0;b<d.length;b++)d[b].call(l,f.Pd,f.reason);r.show(".aax-rating-last")},eN:function(){if(!e&&null!==f.Pd){for(var b=q.Pl(a.ob+" .aax-rating-feedback"),c=0;c<b.length;c++)f.reason[b[c].value]=1,b[c].checked=!1;for(b=0;b<n.length;b++)n[b].call(l,f.Pd,f.reason)}},show:function(b){e=".aax-rating-last"===b;for(var d=c.querySelector(a.ob+" "+b),f=c.querySelector(".aax-popup"),
g=c.querySelectorAll(".show"),l=0;l<g.length;l++)g[l]!==f&&(q.jd(g[l],"show"),q.be(g[l],"hide"));-1<d.className.indexOf("hide")&&q.jd(d,"hide");q.be(d,"show");d=c.querySelector(a.ob+" .aax-optout");".aax-rating"===b?(q.jd(d,"hide"),q.be(d,"show")):(q.jd(d,"show"),q.be(d,"hide"))},Gx:function(){var b=c.querySelector(a.ob+".aax-popup");-1<b.className.indexOf("hide")&&q.jd(b,"hide");q.be(b,"show");e||r.Tw()},kv:function(){var b=c.querySelector(a.ob+".aax-popup");-1<b.className.indexOf("show")&&q.jd(b,
"show");q.be(b,"hide")},Tw:function(){r.show(".aax-rating");for(var b=q.Pl(a.ob+" .aax-rating-feedback"),c=0;c<b.length;c++)b[c].checked=!1;f.Pd=null;f.reason={}}},u=function(){for(var b=c.querySelectorAll(a.ob+" .star-list li"),e=0;e<b.length;e++)q.oi(b[e],"click",r.NN);q.oi(c.querySelector(a.ob+" .aax-rating-feedback .submit button"),"click",r.pN);q.oi(c.querySelector(a.sg),"click",r.Gx);q.oi(c.querySelector(a.ob+" .close-feedback"),"click",function(){r.eN();r.kv()})};l.init=function(){a.Rc&&q.hN();
for(var b in k)k.hasOwnProperty(b)&&"undefined"===typeof a[b]&&(a[b]=k[b]);for(var e in a)a.hasOwnProperty(e)&&(h[e]=a[e]);a.Rc&&q.gN();a.px&&q.zN();if(null===c.querySelector(a.ob))throw"Container selector "+a.ob+" is not found/invalid";if(null===c.querySelector(a.sg))throw"CTA selector "+a.sg+" is not found/invalid";if(a.Ko||0===a.Ko)c.querySelector(a.ob).style.zIndex=a.Ko;if(a.Lo||0===a.Lo)c.querySelector(a.sg).style.zIndex=a.Lo;u();return l};l.ft=function(){return f};l.wO=function(a){q.f(a)&&m.push(a)};
l.vO=function(a){q.f(a)&&d.push(a)};l.uO=function(a){q.f(a)&&n.push(a)};l.config=h;l.Vw=r.Tw;l.Tga={show:r.Gx,Um:r.kv};return l}}});
__ad("postdata",["_","postdataconstants"],function(a,b){function c(){var b={},c=this;this.get=function(a){return b[a]};this.set=function(a,c){b[a]=c;return this};this.Y=function(){return a.extend({},b)};this.Pb=function(c){b=a.extend({},c);return this};this.id=function(b){a.a(b)&&c.set("pid",b);return c.get("pid")};this.Qb=function(b){a.a(b)&&c.set("pfid",b);return c.get("pfid")};this.target=function(b){a.a(b)&&c.set("ptarget",b);return c.get("ptarget")};this.source=function(b){if(a.a(b))c.set("psource",
b);else return c.get("psource")};c.set("pid",g++)}var g=1;c.D=b.D;return c});
__ad("ddagif","pqus _ ff qlf srvwpf ef postdata ie uhv inmemdatasource".split(" "),function(a,b,c,g,k,h,f,m,d,n){function l(c,d){var l=(new f).Pb(d.data),h=l.get("ac");c=l.get("lpx");var p=l.get("aId"),k=l.get("szs");d=l.get("crid");var q=l.get("pvid"),x="refReq"===l.get("type");var y=l.get("pvid");l=l.get("aId");"207"===y?n.for(l).set("sRdOut","1"):n.for(l).set("sRdOut","0");n.set("aid",p);l=k[0][0];var A=k[0][1];y=document.getElementById("aax_standard");y.innerHTML="";l=b.hf("aax_if_aax_standard",
l,A);y.appendChild(l);y=b.zf(l)[1];a:{n.for(p).set("isAAX",!0);if("1"!==n.for(p).get("sRdOut"))try{y.document.open(),y.document.write(h),y.document.close()}catch(C){a.na("Error while rendering the adcode");h=!1;break a}h=!0}y=h;l=!y;A="1"===n.for(p).get("sRdOut");p=(new f).set("status",y).set("type","renderad").set("isEmp",l?"1":"0").set("sz",k[0].join("x")).set("isAaxWon",!0).set("aId",p).set("sRdOut",A);p.target(n.get("tarOg"));p.Qb(n.get("fid"));window.top.postMessage(p.Y(),p.target());x&&b.a(e)?
e.Vw():e=m.Zm(window,q);m.Xr(d,q);h&&c&&g.submit(c,{type:"img",X:["win","plvf"]})}var e=null;return{init:function(){b.A("aaxOnMes","gbl",l)}}});
__ad("displayframecore","_ pqus uhv postdata ie inmemdatasource srvwpf ddagif".split(" "),function(a,b,c,g,k,h,f,m){function d(){var a=(new g).set("phs",!0);a.target(h.get("tarOg"));a.Qb(h.get("fid"));window.top.postMessage(a.Y(),a.target())}function n(b){var c=window.document.createElement("div");c.id="aax_standard";a.Pc("@body:0",100,function(e){e.appendChild(c);a.f(b)&&b()})}b.Gh("AAX");window.aax=window.aax||{};(function(){var c=window.aax.__conf;try{if(a.a(window.name)){var e=JSON.parse(window.name);
a.extend(c,e)}}catch(p){b.na("Failed to read window name")}a.c(c,function(a,b){h.set(b,a)})})();h.set("gdpr","1"===window.aaxSettings.gdpr);h.set("gdprconsent",window.aaxSettings.gdprconsent);h.set("uspst","1"===window.aaxSettings.uspst);h.set("uspcn","1"===window.aaxSettings.uspcn);h.set("icr","1"===window.aaxSettings.icr);a.W.U(window,"message",a.L(function(b){b.data&&b.origin===b.data.src&&b.data.id===a.Xa(h.get("fid"))&&("initRen"===b.data.type||"refReq"===b.data.type)&&a.triggerEvent("aaxOnMes",
"gbl",!0,b)}));return{start:function(){n(d);m.init();k.qr(window)}}});window.__ar(["displayframecore"],function(a){a.start()});
} catch (err) {
    window.aax.err = err;
    window.aax.errConsts = {"name":"aaxDisplayIframe","type":"AAX_DISPLAY_IFRAME","svr":"2021031611_102","servname":"c8-web-22","message":"aaxDisplayIframe encountered an error","path":"\/nerrping.php","customerId":"AAX42WKKE","hostName":"https:\/\/l3.aaxads.com","get":{"userAgent":"userAgent","requrl":"requrl","cid":"cid","img":"img","d":"d"}};var Ta=window.aax.err,Ua=window.aax.errConsts;Ua=Ua||{};Ua.get=Ua.get||{};Ta=Ta||{};var Va={},Ya="",Za=encodeURIComponent(window.navigator.userAgent);Ya=Ta.stack?Ta.stack:Ta.s?Ta.s:Ta.stacktrace?Ta.stacktrace:"No StackTrace";var $a="",ab;for(ab in Ta)Ta.hasOwnProperty&&Ta.hasOwnProperty(ab)&&($a+=ab+" : '"+Ta[ab]+"',");Va.logLevel=3;Va.errorVal={};Va.errorVal.name=Ua.name;Va.errorVal.type=Ua.type;Va.errorVal.svr=Ua.svr;Va.errorVal.servname=Ua.servname;Va.errorVal.message=Ua.message;
Va.errorVal.stack=Ya;Va.errorVal.objTrace=$a;var bb="";bb="object"===typeof JSON&&"undefined"!==typeof JSON.stringify?JSON.stringify(Va):Va.errorVal.name+"@#@"+Va.errorVal.type+"@#@"+Ya+"@#@"+$a;bb=encodeURIComponent("["+bb+"]");var cb=Ua.hostName+Ua.path+"?"+Ua.get.userAgent+"="+Za+"&"+Ua.get.hha+"="+encodeURIComponent(window.location.href)+"&"+Ua.get.cid+"="+Ua.customerId+"&"+Ua.get.Vfa+"=logo.gif&"+Ua.get.d+"="+bb;(new Image).src=cb;
};